// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredients.sql

package sqlc

import (
	"context"
)

const findOrCreateIngredient = `-- name: FindOrCreateIngredient :one
INSERT INTO ingredients (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) FindOrCreateIngredient(ctx context.Context, name string) (Ingredient, error) {
	row := q.db.QueryRow(ctx, findOrCreateIngredient, name)
	var i Ingredient
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, name FROM ingredients ORDER BY name
`

func (q *Queries) ListIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
