// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID   int64
	Name string
}

type Ingredient struct {
	ID   int64
	Name string
}

type Recipe struct {
	ID           int64
	Name         string
	Instructions string
	ImageUrl     string
	Source       string
	Status       string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

type RecipeCategory struct {
	RecipeID   int64
	CategoryID int64
}

type RecipeIngredient struct {
	ID           int64
	RecipeID     int64
	IngredientID int64
	Amount       float64
	UnitID       pgtype.Int8
	Position     int32
}

type Unit struct {
	ID   int64
	Name string
}
