// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddRecipeCategory(ctx context.Context, arg AddRecipeCategoryParams) error
	AddRecipeIngredient(ctx context.Context, arg AddRecipeIngredientParams) (RecipeIngredient, error)
	CountRecipes(ctx context.Context, arg CountRecipesParams) (int64, error)
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	DeleteRecipe(ctx context.Context, id int64) (int64, error)
	DeleteRecipeCategories(ctx context.Context, recipeID int64) error
	DeleteRecipeIngredients(ctx context.Context, recipeID int64) error
	FindOrCreateCategory(ctx context.Context, name string) (Category, error)
	FindOrCreateIngredient(ctx context.Context, name string) (Ingredient, error)
	FindOrCreateUnit(ctx context.Context, name string) (Unit, error)
	GetRecipe(ctx context.Context, id int64) (Recipe, error)
	GetRecipeBySource(ctx context.Context, source string) (Recipe, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListIngredients(ctx context.Context) ([]Ingredient, error)
	ListRecipeCategories(ctx context.Context, recipeID int64) ([]Category, error)
	ListRecipeIngredients(ctx context.Context, recipeID int64) ([]ListRecipeIngredientsRow, error)
	ListUnits(ctx context.Context) ([]Unit, error)
	SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]Recipe, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
}

var _ Querier = (*Queries)(nil)
