// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	AddRecipeCategory(ctx context.Context, arg AddRecipeCategoryParams) error
	AddRecipeIngredient(ctx context.Context, arg AddRecipeIngredientParams) (RecipeIngredient, error)
	CountRecipes(ctx context.Context, arg CountRecipesParams) (int64, error)
	// ON CONFLICT DO NOTHING makes the unique index on source the dedupe itself:
	// the insert either stores the recipe or returns no row, with no window in
	// between for a second importer to slip through. The check-then-act this
	// replaced (GetBySource, then Create) was one query more expensive and could
	// only ever narrow that window, not close it. A conflict surfaces as
	// pgx.ErrNoRows, which the repository translates to ErrDuplicateSource.
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	DeleteRecipe(ctx context.Context, id int64) (int64, error)
	DeleteRecipeCategories(ctx context.Context, recipeID int64) error
	DeleteRecipeIngredients(ctx context.Context, recipeID int64) error
	FindOrCreateCategory(ctx context.Context, name string) (Category, error)
	FindOrCreateIngredient(ctx context.Context, name string) (Ingredient, error)
	FindOrCreateUnit(ctx context.Context, name string) (Unit, error)
	GetRecipe(ctx context.Context, id int64) (Recipe, error)
	GetRecipeBySource(ctx context.Context, source string) (Recipe, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListIngredients(ctx context.Context) ([]Ingredient, error)
	ListRecipeCategories(ctx context.Context, recipeID int64) ([]Category, error)
	ListRecipeIngredients(ctx context.Context, recipeID int64) ([]ListRecipeIngredientsRow, error)
	ListUnits(ctx context.Context) ([]Unit, error)
	SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]Recipe, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
}

var _ Querier = (*Queries)(nil)
