// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recipes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRecipeCategory = `-- name: AddRecipeCategory :exec
INSERT INTO recipe_categories (recipe_id, category_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddRecipeCategoryParams struct {
	RecipeID   int64
	CategoryID int64
}

func (q *Queries) AddRecipeCategory(ctx context.Context, arg AddRecipeCategoryParams) error {
	_, err := q.db.Exec(ctx, addRecipeCategory, arg.RecipeID, arg.CategoryID)
	return err
}

const addRecipeIngredient = `-- name: AddRecipeIngredient :one
INSERT INTO recipe_ingredients (recipe_id, ingredient_id, amount, unit_id, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, recipe_id, ingredient_id, amount, unit_id, position
`

type AddRecipeIngredientParams struct {
	RecipeID     int64
	IngredientID int64
	Amount       float64
	UnitID       pgtype.Int8
	Position     int32
}

func (q *Queries) AddRecipeIngredient(ctx context.Context, arg AddRecipeIngredientParams) (RecipeIngredient, error) {
	row := q.db.QueryRow(ctx, addRecipeIngredient,
		arg.RecipeID,
		arg.IngredientID,
		arg.Amount,
		arg.UnitID,
		arg.Position,
	)
	var i RecipeIngredient
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.IngredientID,
		&i.Amount,
		&i.UnitID,
		&i.Position,
	)
	return i, err
}

const countRecipes = `-- name: CountRecipes :one
SELECT COUNT(DISTINCT r.id) FROM recipes r
LEFT JOIN recipe_categories rc ON rc.recipe_id = r.id
WHERE ($1::text IS NULL OR lower(r.name) LIKE '%' || lower($1::text) || '%')
  AND ($2::bigint IS NULL OR rc.category_id = $2::bigint)
  AND ($3::text IS NULL OR r.status = $3::text)
`

type CountRecipesParams struct {
	Text       pgtype.Text
	CategoryID pgtype.Int8
	Status     pgtype.Text
}

func (q *Queries) CountRecipes(ctx context.Context, arg CountRecipesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecipes, arg.Text, arg.CategoryID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (name, instructions, image_url, source, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, instructions, image_url, source, status, created_at, updated_at
`

type CreateRecipeParams struct {
	Name         string
	Instructions string
	ImageUrl     string
	Source       string
	Status       string
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, createRecipe,
		arg.Name,
		arg.Instructions,
		arg.ImageUrl,
		arg.Source,
		arg.Status,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Instructions,
		&i.ImageUrl,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRecipe = `-- name: DeleteRecipe :execrows
DELETE FROM recipes WHERE id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRecipe, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteRecipeCategories = `-- name: DeleteRecipeCategories :exec
DELETE FROM recipe_categories WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeCategories(ctx context.Context, recipeID int64) error {
	_, err := q.db.Exec(ctx, deleteRecipeCategories, recipeID)
	return err
}

const deleteRecipeIngredients = `-- name: DeleteRecipeIngredients :exec
DELETE FROM recipe_ingredients WHERE recipe_id = $1
`

func (q *Queries) DeleteRecipeIngredients(ctx context.Context, recipeID int64) error {
	_, err := q.db.Exec(ctx, deleteRecipeIngredients, recipeID)
	return err
}

const getRecipe = `-- name: GetRecipe :one
SELECT id, name, instructions, image_url, source, status, created_at, updated_at FROM recipes WHERE id = $1
`

func (q *Queries) GetRecipe(ctx context.Context, id int64) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Instructions,
		&i.ImageUrl,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRecipeBySource = `-- name: GetRecipeBySource :one
SELECT id, name, instructions, image_url, source, status, created_at, updated_at FROM recipes WHERE source = $1
`

func (q *Queries) GetRecipeBySource(ctx context.Context, source string) (Recipe, error) {
	row := q.db.QueryRow(ctx, getRecipeBySource, source)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Instructions,
		&i.ImageUrl,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRecipeCategories = `-- name: ListRecipeCategories :many
SELECT c.id, c.name FROM categories c
JOIN recipe_categories rc ON rc.category_id = c.id
WHERE rc.recipe_id = $1
ORDER BY c.name
`

func (q *Queries) ListRecipeCategories(ctx context.Context, recipeID int64) ([]Category, error) {
	rows, err := q.db.Query(ctx, listRecipeCategories, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecipeIngredients = `-- name: ListRecipeIngredients :many
SELECT ri.ingredient_id, i.name AS ingredient_name, ri.amount, COALESCE(u.name, '') AS unit_name
FROM recipe_ingredients ri
JOIN ingredients i ON i.id = ri.ingredient_id
LEFT JOIN units u ON u.id = ri.unit_id
WHERE ri.recipe_id = $1
ORDER BY ri.position, ri.id
`

type ListRecipeIngredientsRow struct {
	IngredientID   int64
	IngredientName string
	Amount         float64
	UnitName       string
}

func (q *Queries) ListRecipeIngredients(ctx context.Context, recipeID int64) ([]ListRecipeIngredientsRow, error) {
	rows, err := q.db.Query(ctx, listRecipeIngredients, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecipeIngredientsRow
	for rows.Next() {
		var i ListRecipeIngredientsRow
		if err := rows.Scan(
			&i.IngredientID,
			&i.IngredientName,
			&i.Amount,
			&i.UnitName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchRecipes = `-- name: SearchRecipes :many
SELECT DISTINCT r.id, r.name, r.instructions, r.image_url, r.source, r.status, r.created_at, r.updated_at FROM recipes r
LEFT JOIN recipe_categories rc ON rc.recipe_id = r.id
WHERE ($3::text IS NULL OR lower(r.name) LIKE '%' || lower($3::text) || '%')
  AND ($4::bigint IS NULL OR rc.category_id = $4::bigint)
  AND ($5::text IS NULL OR r.status = $5::text)
ORDER BY r.name
LIMIT $1 OFFSET $2
`

type SearchRecipesParams struct {
	Limit      int32
	Offset     int32
	Text       pgtype.Text
	CategoryID pgtype.Int8
	Status     pgtype.Text
}

func (q *Queries) SearchRecipes(ctx context.Context, arg SearchRecipesParams) ([]Recipe, error) {
	rows, err := q.db.Query(ctx, searchRecipes,
		arg.Limit,
		arg.Offset,
		arg.Text,
		arg.CategoryID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recipe
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Instructions,
			&i.ImageUrl,
			&i.Source,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
SET name = $2, instructions = $3, image_url = $4, status = $5, updated_at = now()
WHERE id = $1
RETURNING id, name, instructions, image_url, source, status, created_at, updated_at
`

type UpdateRecipeParams struct {
	ID           int64
	Name         string
	Instructions string
	ImageUrl     string
	Status       string
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRow(ctx, updateRecipe,
		arg.ID,
		arg.Name,
		arg.Instructions,
		arg.ImageUrl,
		arg.Status,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Instructions,
		&i.ImageUrl,
		&i.Source,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
