// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package sqlc

import (
	"context"
)

const findOrCreateUnit = `-- name: FindOrCreateUnit :one
WITH existing AS (
    SELECT id, name FROM units WHERE name = $1::text
), inserted AS (
    INSERT INTO units (name)
    SELECT $1::text WHERE NOT EXISTS (SELECT 1 FROM existing)
    ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
    RETURNING id, name
)
SELECT id, name FROM existing
UNION ALL
SELECT id, name FROM inserted
`

type FindOrCreateUnitRow struct {
	ID   int64
	Name string
}

// Returns the unit row with this name, inserting it first only if there is none.
//
// It reads before it writes. The plain INSERT ... ON CONFLICT DO UPDATE this
// replaces went through the insert path on every call: it spent a sequence
// value, wrote a new row version and took a row lock even when the row existed,
// which is nearly always. Since recipe writes resolve names inside their own
// transaction, that lock was held until the recipe committed, so two writes
// naming the same unit queued behind each other, and two naming a pair of them
// in opposite order could deadlock.
//
// The INSERT runs only when the read found nothing, and keeps DO UPDATE for the
// one case the read cannot see: a row another transaction committed after this
// statement's snapshot. DO UPDATE, unlike DO NOTHING, still returns that row,
// so the statement always yields exactly one.
func (q *Queries) FindOrCreateUnit(ctx context.Context, name string) (FindOrCreateUnitRow, error) {
	row := q.db.QueryRow(ctx, findOrCreateUnit, name)
	var i FindOrCreateUnitRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT id, name FROM units ORDER BY name
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
