// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: units.sql

package sqlc

import (
	"context"
)

const findOrCreateUnit = `-- name: FindOrCreateUnit :one
INSERT INTO units (name) VALUES ($1)
ON CONFLICT (name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

func (q *Queries) FindOrCreateUnit(ctx context.Context, name string) (Unit, error) {
	row := q.db.QueryRow(ctx, findOrCreateUnit, name)
	var i Unit
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listUnits = `-- name: ListUnits :many
SELECT id, name FROM units ORDER BY name
`

func (q *Queries) ListUnits(ctx context.Context) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Unit
	for rows.Next() {
		var i Unit
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
